language: objective-c
osx_image: xcode9.4

before_install:
  - gem install xcpretty-travis-formatter;
  - gem install cocoapods --no-document --quiet;

script:
  - set -o pipefail && bundle exec fastlane travis

