# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.

fastlane_version "1.68.0"

default_platform :ios

platform :ios do
  before_all do

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  lane :release do
    ensure_git_status_clean
    increment_build_number
    increment_version_number(bump_type: "minor")
    jazzy
    commit_version_bump
    add_git_tag(tag: "v#{lane_context[SharedValues::VERSION_NUMBER]}")
    push_to_git_remote

    set_github_release(
      repository_name: "mirego/taylor-ios",
      api_token: ENV['GITHUB_TOKEN'],
      name: "Taylor v#{lane_context[SharedValues::VERSION_NUMBER]}",
      tag_name: "v#{lane_context[SharedValues::VERSION_NUMBER]}",
      upload_assets: ["docs/docsets/Taylor.tgz"]
    )

    reset_git_repo
  end

end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
